version: "3.9"

services:
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./:/app
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb
    volumes:
      - postgresql-data:/var/lib/postgresql/data

volumes:
  postgresql-data:
